engines:
    phpmd:
        enabled: true
        config:
            file_extensions: "php"
            rulesets: "cleancode,codesize,controversial,design,unusedcode"

    phpcodesniffer:
        enabled: true
        config:
            standard: "PSR1,PSR2"
exclude_paths:
- "app/"
- "bin/"
- "config/"
- "var/"
- "web/"
- "vendor/"
