<?php

namespace AppBundle\Repository;

/**
 * QueueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QueueRepository extends \Doctrine\ORM\EntityRepository
{
}
