<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Queue;

/**
 * QueueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QueueRepository extends \Doctrine\ORM\EntityRepository
{
    public function delete(Queue $queue)
    {
        $this->_em->remove($queue);
        $this->_em->flush();
    }
}
